### ISSUE TITLE
Intoroduce a formatter to the repo

### ISSUE THREAD

**Issue by zaporter** [sdumetz/node-wayland-client#1]
Hi! I'd love to contribute to your repo, but my editor keeps auto-formatting the files. Makes it kind of painful to work in the repo.

Would you be open to adding `prettier` to format your code?

Its as simple as adding a `.prettierignore`, a `.prettierrc`, and adding a target like `"format": "prettier . --write"` to your `package.json`

See this diff to see how you feel about the styling:

https://github.com/sdumetz/node-wayland-client/compare/main...zaporter:node-wayland-client:zp/formatter?expand=1

(you should probably author this commit to avoid changing the git-blame for most of the repo)

(I know you like to write your types as `name :type` instead of `name: type`, but I couldn't find a way to get prettier to do that :cry: )

**Comment by sdumetz** [comment]
Maybe just disable autoformatting in your editor?

I don't like being bothered by computers about forgetting a space somewhere.

FWIW, I don't care if you provide a PR with different code formatting than what I'd have done as long as it's readable. Even if your change some formatting around your changes, I'll probably survive.

**Comment by zaporter** [comment]
> I don't like being bothered by computers about forgetting a space somewhere.

Formatters are not linters -- prettier will never fail because of a space, it will just auto-add it. 

> FWIW, I don't care if you provide a PR with different code formatting than what I'd have done as long as it's readable. Even if your change some formatting around your changes, I'll probably survive.

Alright! Sounds good for now! Happy to keep my formatter confined to my changes.
